/**
 * water - NetHack special level
 * Converted from: water.lua
 */

import * as des from '../sp_lev.js';

export async function generate() {
    // NetHack endgame water.lua	$NHDT-Date: 1652196038 2022/5/10 15:20:38 $  $NHDT-Branch: NetHack-3.7 $:$NHDT-Revision: 1.1 $
    // Copyright (c) 1989 by Jean-Christophe Collet
    // Copyright (c) 1992,1993 by Izchak Miller, David Cohrs,
    // && Timo Hakulinen
    // NetHack may be freely redistributed.  See license for details.
    // 
    des.level_init({ style: "solidfill", fg: " " });

    des.level_flags("mazelevel", "noteleport", "hardfloor", "shortsighted");
    await des.message("You find yourself suspended in an air bubble surrounded by water.");
    // The player lands upon arrival to an air bubble
    // within the leftmost third of the level.  The
    // portal to the next level is randomly located in an air
    // bubble within the rightmost third of the level.
    // Bubbles are generated by special code in mkmaze.c for now.
    await des.map(`\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
`);
    await des.teleport_region({ region: [0,0,25,19] });
    await des.levregion({ type: "portal", region: [51,0,75,19], name: "astral" });
    // A fisherman's dream...args
    await des.monster("giant eel");
    await des.monster("giant eel");
    await des.monster("giant eel");
    await des.monster("giant eel");
    await des.monster("giant eel");
    await des.monster("giant eel");
    await des.monster("giant eel");
    await des.monster("giant eel");
    await des.monster("electric eel");
    await des.monster("electric eel");
    await des.monster("electric eel");
    await des.monster("electric eel");
    await des.monster("electric eel");
    await des.monster("electric eel");
    await des.monster("electric eel");
    await des.monster("electric eel");
    await des.monster("kraken");
    await des.monster("kraken");
    await des.monster("kraken");
    await des.monster("kraken");
    await des.monster("kraken");
    await des.monster("kraken");
    await des.monster("kraken");
    await des.monster("kraken");
    await des.monster("kraken");
    await des.monster("shark");
    await des.monster("shark");
    await des.monster("shark");
    await des.monster("shark");
    await des.monster("piranha");
    await des.monster("piranha");
    await des.monster("piranha");
    await des.monster("piranha");
    await des.monster("jellyfish");
    await des.monster("jellyfish");
    await des.monster("jellyfish");
    await des.monster("jellyfish");
    await des.monster(";");
    await des.monster(";");
    await des.monster(";");
    await des.monster(";");
    // These guys feel like home here
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });
    await des.monster({ id: "water elemental", peaceful: 0 });



    return await des.finalize_level();
}
